Shop.MVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shop.DataAccess.Data.Repository.IRepository;
using Shop.Models;
using Shop.Models.ViewModels;
using Shop.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Shop.MVC.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get(string status = null)
        {
            List<OrderDetailsVM> orderListVM = new List<OrderDetailsVM>();

            IEnumerable<OrderHeader> orderHeaderList;

            if(User.IsInRole(SD.CustomerRole))
            {
                //retrieve all orders for that customer
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                orderHeaderList = _unitOfWork.OrderHeader.GetAll(u => u.UserId == claim.Value, null, "ApplicationUser");
            }
            else
            {
                orderHeaderList = _unitOfWork.OrderHeader.GetAll(null, null, "ApplicationUser");
            }
            if(status=="cancelled")
            {
                orderHeaderList = orderHeaderList.Where(s => s.Status == SD.StatusCancelled || s.Status == SD.StatusRefunded);
            }
            else
            {
                if(status == "completed")
                {
                    orderHeaderList = orderHeaderList.Where(s => s.Status == SD.StatusCompleted);
                }
                else
                {
                    orderHeaderList = orderHeaderList.Where(s => s.Status == SD.StatusReady || s.Status == SD.StatusCancelled || s.Status == SD.StatusRefunded || s.Status == SD.PaymentStatusRejected);
                }
            }
            foreach(OrderHeader item in orderHeaderList)
            {
                OrderDetailsVM individual = new OrderDetailsVM
                {
                    OrderHeader = item,
                    OrderDetails = _unitOfWork.OrderDetails.GetAll(o => o.OrderId == item.Id).ToList()
                };
            orderListVM.Add(individual);
            }
            return Json(new { data = orderListVM });
        }
    }
}

Shop.MVC/Pages/Admin/Order/ManageOrder.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.DataAccess.Data.Repository.IRepository;
using Shop.Models;
using Shop.Models.ViewModels;
using Shop.Utility;
using Stripe;

namespace Shop.MVC.Pages.Admin.Order
{
    public class ManageOrderModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public ManageOrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public List<OrderDetailsVM> orderDetailsVM { get; set; }

        public void OnGet()
        {
            orderDetailsVM = new List<OrderDetailsVM>();

            List<OrderHeader> orderHeaderList = _unitOfWork.OrderHeader.GetAll(o => o.Status == SD.StatusSubmitted || o.Status == SD.StatusInProcess)
                .OrderByDescending(u => u.PickUpTime).ToList();
            foreach (OrderHeader item in orderHeaderList)
            {
                OrderDetailsVM individual = new OrderDetailsVM
                {
                    OrderHeader = item,
                    OrderDetails = _unitOfWork.OrderDetails.GetAll(o => o.OrderId == item.Id).ToList()
                };
                orderDetailsVM.Add(individual);
            }
        }

        public IActionResult OnPostOrderPrepare(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefualt(s => s.Id == orderId);
            orderHeader.Status = SD.StatusInProcess;
            _unitOfWork.Save();
            return RedirectToPage("ManagerOrder");
        }
        public IActionResult OnPostOrderReady(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefualt(s => s.Id == orderId);
            orderHeader.Status = SD.StatusReady;
            _unitOfWork.Save();
            return RedirectToPage("ManagerOrder");
        }
        public IActionResult OnPostOrderCancel(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefualt(s => s.Id == orderId);
            orderHeader.Status = SD.StatusCancelled;
            _unitOfWork.Save();
            return RedirectToPage("ManagerOrder");
        }
        public IActionResult OnPostOrderRefund(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefualt(s => s.Id == orderId);
            //refund amoount
            var options = new RefundCreateOptions
            {
                Amount = Convert.ToInt32(orderHeader.OrderTotal*100),
                Reason = RefundReasons.RequestedByCustomer,
                Charge = orderHeader.TransactionId,
            };
            var service = new RefundService();
            Refund refund = service.Create(options);

            orderHeader.Status = SD.StatusRefunded;
            _unitOfWork.Save();
            return RedirectToPage("ManagerOrder");
        }

    }
}

Shop.MVC/Pages/Admin/Order/OrderDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.DataAccess.Data.Repository.IRepository;
using Shop.Models;
using Shop.Models.ViewModels;

namespace Shop.MVC.Pages.Admin.Order
{
    public class OrderDetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderDetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public OrderDetailsVM orderDetailsVM { get; set; }
        public void OnGet(int id)
        {
            orderDetailsVM = new OrderDetailsVM()
            {
            OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefualt(m => m.Id == id),
            OrderDetails = _unitOfWork.OrderDetails.GetAll(m => m.OrderId == id).ToList()
            };
            orderDetailsVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefualt(u => u.Id == orderDetailsVM.OrderHeader.UserId);
        }
    }
}

Shop.MVC/Pages/Admin/Order/OrderList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Shop.MVC.Pages.Admin.Order
{
    public class OrderListModel : PageModel
    {
        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

Shop.MVC/Pages/Admin/Order/ManageOrder.cshtml
@page
@model Shop.MVC.Pages.Admin.Order.ManageOrderModel
@using Shop.Utility 

<h1 class="text-primary py-3">Manage Order's</h1>
<form method="post">
    @if (Model.orderDetailsVM.Count > 0)
    {
        <div class="container row bg-white p-2 border mb-3 rounded"> 
             @foreach(var item in Model.orderDetailsVM)
             {
        <div class="container row bg-white p-2 border mb-3 rounded">

            <div class="col-12 pb-3 pt-3 mt-4 border  rounded">
                <div class="backgroundWhiteBorder10Padding">
                    <div class="row">
                        <div class="col-4">
                            Order Number : @item.OrderHeader.Id
                            <ul class="text-info">
                                @foreach (var details in item.OrderDetails)
                                {
                                    <li> @details.Name x @details.Count </li>
                                }

                                </ul>
                        </div>
                        <div class="col-4 pb-2">
                            <div class="input-group pb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text">Time</span>
                                </div>
                                <input type="text" class="border rounded form-control" readonly value="@item.OrderHeader.PickUpTime" />
                            </div>
                            @{ 
                                var comments = item.OrderHeader.Comments;
                                if(comments == null || comments.Trim().Length ==0)
                                {
                                    item.OrderHeader.Comments = "No instructions";
                                }
                            }
                            <textarea readonly class="rounded border form-control" style="width:100%;height:75px;"></textarea>
                        </div>
                        <div class="col-3 offset-1 d-flex align-content-center">
                            <div class="col-12">

                                @if (item.OrderHeader.Status.Equals(SD.StatusSubmitted))
                                {
                                    <button type="submit" class="btn btn-primary form-control mb-3" asp-page="OrderPrepare" asp-route-OrderId="@item.OrderHeader.Id">
                                        <i class="fas fa-check"></i> &nbsp; Start Cooking
                                    </button>
                                }
                                else
                                {
                                    if (item.OrderHeader.Status.Equals(SD.StatusInProcess)) 
                                    {
                                        <button type="submit" class="btn btn-success form-control mb-3" asp-page="OrderReady" asp-route-OrderId="@item.OrderHeader.Id">>
                                            <i class="fas fa-flag-checkered"></i> &nbsp; Order Ready
                                        </button>
                                    }
                                }


                                <button type="submit" class="btn btn-warning form-control mb-3" asp-page="OrderCancel" asp-route-OrderId="@item.OrderHeader.Id">>
                                    <i class="fas fa-times"></i> &nbsp; Cancel Order
                                </button>
                                <button type="submit" class="btn btn-danger form-control mb-3" asp-page="OrderRefund" asp-route-OrderId="@item.OrderHeader.Id">>
                                    <i class="fas fa-times"></i> &nbsp; Refund Order
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
                                }
        </div>
    }

</form>

Shop.MVC/Pages/Admin/Order/OrderDetails.cshtml
@page
@model Shop.MVC.Pages.Admin.Order.OrderDetailsModel
@using Shop.Utility
@{
}


<form method="post">
    <div class="border ml-1 backgroundWhite mt-4">
        <div class="row pb-1">
            <div class="col-12 col-md-6 ">
                <p class="h2  text-primary">Order Details</p>
            </div>
            <div class="col-12 col-md-4 offset-md-2">
                <a asp-page="/Admin/Order/OrderList" class="btn btn-success form-control">Back to Orders </a>
            </div>
        </div>
        <hr />

        <div class="row pt-2">

            <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
                <input type="hidden" asp-for="orderDetailsVM.OrderHeader.Id" />
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label>Name</label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetailsVM.OrderHeader.PickupName" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label><label asp-for="orderDetailsVM.OrderHeader.ApplicationUser.Email"></label></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetailsVM.OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label><label asp-for="orderDetailsVM.OrderHeader.ApplicationUser.PhoneNumber"></label></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetailsVM.OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label><label asp-for="orderDetailsVM.OrderHeader.OrderTotal"></label></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetailsVM.OrderHeader.OrderTotal" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label><label asp-for="orderDetailsVM.OrderHeader.OrderDate"></label></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input value="@Model.orderDetailsVM.OrderHeader.PickUpTime.ToShortDateString() @Model.orderDetailsVM.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label><label asp-for="orderDetailsVM.OrderHeader.Comments"></label></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="orderDetailsVM.OrderHeader.Comments" disabled class="form-control" />
                    </div>
                </div>

            </div>



            <div class="col-lg-4 col-12">
                <h4 class="d-flex justify-content-between align-content-center mb-3">
                    <span class="text-muted">Order ID: </span>
                    <span class="badge badge-secondary badge-pill">@Model.orderDetailsVM.OrderHeader.Id</span>
                </h4>
                <ul class="list-group mb-3">
                    @foreach (var details in Model.orderDetailsVM.OrderDetails)
                    {
                        <li class="list-group-item d-flex justify-content-between">
                            <div>
                                <h6 class="my-0">@details.Name</h6>
                                <small class="text-muted">Quantity : @details.Count</small>
                            </div>
                            <span class="text-muted">$@(details.Price * details.Count)</span>
                        </li>
                    }

                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <span class="text-info"> Total (USD)</span>
                        <strong class="text-info">$@Model.orderDetailsVM.OrderHeader.OrderTotal</strong>
                    </li>

                </ul>
                @if (Model.orderDetailsVM.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole)))
                {
                    <button type="submit" class="btn btn-success form-control" asp-page-handler="OrderConfirm" asp-route-OrderId="@Model.orderDetailsVM.OrderHeader.Id"><i class="far fa-thumbs-up"></i> Confirm Pickup</button>
                }
                else
                {

                    <button type="submit" disabled class="btn btn-info form-control">@Model.orderDetailsVM.OrderHeader.Status</button>
                }
                @if ((User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole))
                   && (Model.orderDetailsVM.OrderHeader.Status.Equals(SD.StatusSubmitted)
                   || Model.orderDetailsVM.OrderHeader.Status.Equals(SD.StatusReady)
                   || Model.orderDetailsVM.OrderHeader.Status.Equals(SD.StatusInProcess)))
                {
                    <div class="row pt-1">
                        <div class="col-6">
                            <button type="submit" class="btn btn-warning form-control" asp-page-handler="OrderCancel" asp-route-OrderId="@Model.orderDetailsVM.OrderHeader.Id"><i class="fas fa-times"></i> Cancel Order</button>
                        </div>
                        <div class="col-6">
                            <button type="submit" class="btn btn-danger form-control" asp-page-handler="OrderRefund" asp-route-OrderId="@Model.orderDetailsVM.OrderHeader.Id"><i class="fas fa-times"></i> Refund Order</button>
                        </div>
                    </div>


                }


            </div>

        </div>
    </div>
</form>

Shop.MVC/Pages/Admin/Order/OrderList.cshtml
@page
@model Shop.MVC.Pages.Admin.Order.OrderListModel
@{
    ViewData["Title"] = "OrderList";
}

@{ 
    var status = HttpContext.Request.Query["status"];
    var cancelled = "text-primary";
    var completed = "text-primary";
    var inProcess = "text-primary";

    if(status == cancelled)
    {
        cancelled = "active text-white";
    }
    else
    {
        if(status == "completed")
        {
            completed = "active text-white";
        }
        else
        {
            inProcess = "active text-whtie";
        }
    }
 }

<div class="border backgroundWhite container">
    <div class="d-flex justify-content-between mb-3">
        <div class="p-2">
            <h2 class="text-primary">Order List</h2>
        </div>
        <div class="p-2">
            <ul class="list-group list-group-horizontal-sm">
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="cancelled">
                    <li class="list-group-item @cancelled"> Cnacelled </li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="completed">
                    <li class="list-group-item @completed"> Completed </li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="inProecess">
                    <li class="list-group-item @inProcess"> Inprocess </li>
                </a>
            </ul>
            <a asp-page="Upsert" class="btn btn-primary"><i class="fas fa-plus"></i> &nbsp; Create New</a>
        </div>
    </div>
    <br /><br />
    <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Order Total</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/order.js"></script>
}